name: pyinstaller
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: install pyinstaller
        run: pip install pyinstaller
      - name: Build executable
        run: |
          pyinstaller sha256.py -F
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sha256-windows-exe
          path: dist/sha256.exe